name: toppr1
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  font_awesome_flutter: ^10.3.0
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  build_runner: ^2.3.2
  flutter_tex: ^4.0.3+4
  cached_network_image: 
  sliver_header_delegate:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true 
  assets:
    - assets/images/
    - json/maths/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Karla
      fonts:
        # - asset: assets/fonts/Karla-Bold.ttf
        - asset: assets/fonts/Karla-Regular.ttf
        # - asset: assets/fonts/Karla-SemiBold.ttf
        # - asset: assets/fonts/Karla-Medium.ttf
        # - asset: assets/fonts/Karla-Light.ttf
        # - asset: assets/fonts/Karla-Italic.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
 
  